# Generated by Django 3.0.3 on 2020-05-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200522_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='one'),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='one'),
        ),
    ]
